
import Foundation
class Database  {
    static var TABLE_EMPLOYEE = "EmployeeDetails";
    static var COLUMN_EMP_NAME = "Name";
    static var COLUMN_EMP_ID = "EmpId";
    static var COLUMN_UNIQUE_ID = "UniqueId";
    static var COLUMN_EMP_PHONE = "Number";
    static var COLUMN_EMP_MAIL = "MailId";
    static var COLUMN_EMP_GENDER = "Gender";
    static var COLUMN_EMP_STATUS = "Status";
    static var COLUMN_EMP_ADDRESS = "Address";
    static var COLUMN_EMP_DEPT_ID = "DepartmentId";
    static var COLUMN_EMP_REPORTING_ID = "ReportingId";
    static var COLUMN_EMP_LOCATION = "Location"
    static var COLUMN_EMP_POSITION = "Position"
    
    static var TABLE_NOTIFICATION = "Notifications";
    static var COLUMN_NOTIF_ID = "NotificationId";
    static var COLUMN_NOTIF_SUBJECT = "Subject";
    static var COLUMN_NOTIF_DETAILS = "Notification";
    static var COLUMN_NOTIF_LIKES = "Likes";
    static var COLUMN_NOTIF_SENDER_ID = "NotificationSender";
    static var COLUMN_NOTIF_DATE = "NotificationDate"
    static var COLUMN_NOTIF_DEPT = "DepartmentID";
    
    static var TABLE_READ_NOTIFICATION = "ReadNotification";
    static var COLUMN_NOTIF_READBY = "NotifReadId";
    static var COLUMN_NOTIF_STATUS = "NotifStatus";
    
    static var TABLE_NOTIF_LIKES = "NotifLikes"
    static var COLUMN_NOTIF_LIKER_ID = "NotifLikerId"
    
    static var TABLE_QUERY = "Questions";
    static var TABLE_QUERY_REPLIES = "Replies";
    static var COLUMN_QUERY_ID = "QueryID";
    static var COLUMN_REPLY_ID = "ReplyID";
    static var COLUMN_QUERY_SENDER = "SenderId";
    static var COLUMN_QUERY_RECIEVER = "RecieverId";
    static var COLUMN_QUERY_REPLIES = "Reply";
    static var COLUMN_QUERY_REPLIER_ID = "ReplierId";
    static var COLUMN_REPLY_SENDER = "ReplierId";
    static var COLUMN_QUERY_QUESTION = "queryAsked";
    static var COLUMN_QUERY_SUBJECT  = "QuerySubject"
    static var COLUMN_QUERY_DATE = "QueryDate"
    
    static var TABLE_ATTENDANCE = "Attendance";
    static var COLUMN_CHECK_IN_TIME = "CheckInTime";
    static var COLUMN_CHECK_OUT_TIME = "CheckOutTime";
    static var COLUMN_ATTEND_STATUS = "AttendStatus";
    static var COLUMN_DATE_DETAILS = "Date";
    
    static var TABLE_TASK = "Task";
    static var COLUMN_TASK_ID = "TaskId"
    static var COLUMN_TASK_EMPID = "EmpId";
    static var COLUMN_TASK_NAME = "TaskName";
    static var COLUMN_TASK_DETAIL = "TaskDetail";
    static var COLUMN_TASK_STARTDATE = "StartDate";
    static var COLUMN_TASK_ENDDATE = "EndDate";
    static var COLUMN_TASK_STATUS = "Status";
    static var COLUMN_TASK_ASSIGNER = "TaskAssigner"
    
    static var TABLE_DEPARTMENT = "Department";
    static var COLUMN_DEPARTMENT_ID = "DepartmentID";
    static var COLUMN_DEPARTMENT_NAME = "DepartmentName";
    static var COLUMN_DEPARTMENT_HEAD_ID = "DepartmentHeadId";
    static var COLUMN_DEPARTMENT_DESCRIPTION = "Description";
    static var COLUMN_DEPARTMENT_MAILID = "Mail Id"
    static var COLUMN_DEPT_UUID="DepartmentUuid";
    
    static var TABLE_HOLIDAY_LIST = "Holiday";
    static var COLUMN_HOLIDAY_DATE = "HolidayDate";
    static var COLUMN_HOLIDAY_TYPE = "HolidayType";
    static var COLUMN_HOLIDAY_REASON = "Reason";
    
    static var TABLE_INDIVIDUAL_NOTIF = "IndividualNotification"
    
    static var TABLE_APPLIED_LEAVE = "LeaveApplied";
    static var COLUMN_REASON_ID = "ReasonId";
    static var COLUMN_LEAVE_START_DATE = "StartDate";
    static var COLUMN_LEAVE_END_DATE = "EndDate";
    static var COLUMN_LEAVE_DETAILS = "LeaveDetails";
    
    
    static var TABLE_INSERT_COLUMNS = "InsertColumns";
    static var COLUMN_INSERT_COLUMN_STATUS = "status";
    
    static var COLUMN_NOTIF_RECIEVER_ID = "Reciever"
    
    static var TABLE_PERFORMANCE = "Performance"
    static var COLUMN_PERFORMANCE_SPONTANITY = "Spontanity"
    static var COLUMN_PERFORMANCE_RESPONSIVENESS = "Responsiveness"
    static var COLUMN_PERFORMANCE_TIME_MANAGEMENT = "TimeManagement"
    static var COLUMN_PERFORMANCE_ENTHUSAISM = "Enthusaism"
    static var COLUMN_PERFORMANCE_OVERALL_PERFORMANCE = "OverallPerformance"
    static var COLUMN_PERFORMANCE_COMMENTS = "Comments"
    static var COLUMN_PERFORMANCE_DATE = "Date"
    
    static var TABLE_QUERY_HANDLER = "QueryHandler"
    static var COLUMN_QUERY_TYPE = "QueryType"
    static var COLUMN_QUERY_INCHARGE = "QueryIncharge"
    
    
    
    

    
    static var CREATE_TABLE_EMPLOYEE = "CREATE TABLE IF NOT EXISTS " + TABLE_EMPLOYEE + "("
        + COLUMN_EMP_NAME + " TEXT, " + COLUMN_EMP_ID + " INTEGER PRIMARY KEY, " + COLUMN_UNIQUE_ID
        + " TEXT ," + COLUMN_EMP_PHONE + " TEXT, " + COLUMN_EMP_MAIL + " TEXT, " + COLUMN_EMP_GENDER + " TEXT, "
        + COLUMN_EMP_STATUS + " TEXT DEFAULT 'CHECK OUT', " + COLUMN_EMP_ADDRESS + " TEXT ," + COLUMN_EMP_DEPT_ID
        + " TEXT ," + COLUMN_EMP_REPORTING_ID + " TEXT ," + COLUMN_EMP_LOCATION + " TEXT ," + COLUMN_EMP_POSITION+");";
    
    static var CREATE_TABLE_DEPARTMENT = "CREATE TABLE IF NOT EXISTS " + TABLE_DEPARTMENT + "("
        + COLUMN_DEPARTMENT_ID + " INTEGER, "+COLUMN_DEPT_UUID+" TEXT, " + COLUMN_DEPARTMENT_NAME + " TEXT ," + COLUMN_DEPARTMENT_HEAD_ID
        + " TEXT, " + COLUMN_DEPARTMENT_DESCRIPTION + " TEXT)";
    
    static var CREATE_TABLE_NOTIFICATION = "CREATE TABLE IF NOT EXISTS " + TABLE_NOTIFICATION + " ( "
        + COLUMN_NOTIF_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_NOTIF_SUBJECT + " TEXT, "
        + COLUMN_NOTIF_DETAILS + " TEXT ," + COLUMN_NOTIF_LIKES + " INTEGER DEFAULT 0 ," + COLUMN_NOTIF_SENDER_ID + " TEXT ,"+COLUMN_NOTIF_DATE+" INT , \(COLUMN_NOTIF_DEPT) TEXT );";
    
    static var CREATE_TABLE_INDIVIDUAL_NOTIFICATION = "CREATE TABLE IF NOT EXISTS " + TABLE_INDIVIDUAL_NOTIF + " ( "
        + COLUMN_NOTIF_ID + " INTEGER PRIMARY KEY AUTOINCREMENT, " + COLUMN_NOTIF_SUBJECT + " TEXT, "
    + COLUMN_NOTIF_DETAILS + " TEXT ," + COLUMN_NOTIF_LIKES + " INTEGER ," + COLUMN_NOTIF_SENDER_ID + " TEXT ,"+COLUMN_NOTIF_DATE+" INT , \(COLUMN_NOTIF_RECIEVER_ID) TEXT, \(COLUMN_NOTIF_STATUS) TEXT  DEFAULT 'unread');";
    
    
    static var CREATE_TABLE_QUERY = "CREATE TABLE IF NOT EXISTS " + TABLE_QUERY + " ( "
        + COLUMN_QUERY_ID + " TEXT," + COLUMN_QUERY_SENDER + " TEXT, " + COLUMN_QUERY_RECIEVER + " TEXT, "
        + COLUMN_QUERY_QUESTION + " TEXT,  \(COLUMN_QUERY_SUBJECT) TEXT, \(COLUMN_QUERY_DATE) INTEGER );";
    
    static var CREATE_TABLE_QUERY_REPLIES = "CREATE TABLE IF NOT EXISTS " + TABLE_QUERY_REPLIES + " ( "
        + COLUMN_QUERY_ID + " TEXT, " + COLUMN_QUERY_REPLIES + " TEXT, " + COLUMN_REPLY_SENDER + " TEXT, "
        + COLUMN_QUERY_DATE + " INTEGER );";
    
    static var CREATE_TABLE_ATTENDANCE = "CREATE TABLE IF NOT EXISTS " + TABLE_ATTENDANCE + "( "
        + COLUMN_UNIQUE_ID + " TEXT, " + COLUMN_DATE_DETAILS + " INTEGER, " + COLUMN_CHECK_IN_TIME + " INTEGER, "
        + COLUMN_CHECK_OUT_TIME + " INTEGER )";
    
    static var CREATE_TABLE_TASK = "CREATE TABLE IF NOT EXISTS " + TABLE_TASK + "( \(COLUMN_TASK_ID) TEXT ," + COLUMN_TASK_EMPID
        + " TEXT ," + COLUMN_TASK_NAME + " TEXT," + COLUMN_TASK_DETAIL + " TEXT,"  + COLUMN_TASK_STARTDATE + " INTEGER," + COLUMN_TASK_ENDDATE + " INTEGER," + COLUMN_TASK_STATUS
        + " TEXT, "+COLUMN_TASK_ASSIGNER+" TEXT)";
    
    static var CREATE_TABLE_APPLIED_LEAVE = "CREATE TABLE IF NOT EXISTS " + TABLE_APPLIED_LEAVE + "("
        + COLUMN_UNIQUE_ID + " TEXT, " + COLUMN_REASON_ID + " TEXT, " + COLUMN_LEAVE_START_DATE + " INTEGER, "
        + COLUMN_LEAVE_END_DATE + " INTEGER, " + COLUMN_LEAVE_DETAILS + " TEXT, " + COLUMN_DEPARTMENT_ID + " TEXT )";
    
    static var CREATE_TABLE_NOTIFICATION_READ = "CREATE TABLE IF NOT EXISTS " + TABLE_READ_NOTIFICATION
        + "(" + COLUMN_NOTIF_ID + " INTEGER ," + COLUMN_NOTIF_READBY + " TEXT ," + COLUMN_NOTIF_STATUS
        +  " TEXT  DEFAULT 'unread' )";
    
    static var CREATE_TABLE_CHECK = "CREATE TABLE IF NOT EXISTS "+TABLE_INSERT_COLUMNS+" ("+COLUMN_INSERT_COLUMN_STATUS+" INTEGER );";
    
    static var CREATE_TABLE_HOLIDAY = "CREATE TABLE IF NOT EXISTS  \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE) INTEGER, \(COLUMN_HOLIDAY_TYPE) TEXT, \(COLUMN_HOLIDAY_REASON) TEXT )"
    
    static var CREATE_TABLE_QUERY_HANDLER = "CREATE TABLE IF NOT EXISTS \(TABLE_QUERY_HANDLER) ( \(COLUMN_QUERY_TYPE) TEXT, \(COLUMN_QUERY_INCHARGE) TEXT) "
    
    static var CREATE_TABLE_PERFORMANCE = "CREATE TABLE IF NOT EXISTS \(TABLE_PERFORMANCE) ( \(COLUMN_PERFORMANCE_RESPONSIVENESS) INTEGER, \(COLUMN_PERFORMANCE_SPONTANITY) INTEGER, \(COLUMN_PERFORMANCE_TIME_MANAGEMENT) INTEGER, \(COLUMN_PERFORMANCE_ENTHUSAISM) INTEGER, \(COLUMN_PERFORMANCE_OVERALL_PERFORMANCE) INTEGER, \(COLUMN_PERFORMANCE_COMMENTS) TEXT ,\(COLUMN_PERFORMANCE_DATE) INTEGER, \(COLUMN_UNIQUE_ID) TEXT)"
    
    static var CREATE_TABLE_NOTIF_LIKES = "CREATE TABLE IF NOT EXISTS \(TABLE_NOTIF_LIKES) ( \(COLUMN_NOTIF_LIKER_ID) TEXT , \(COLUMN_NOTIF_ID) INTEGER )"
    

    
    static var table = [ CREATE_TABLE_EMPLOYEE, CREATE_TABLE_DEPARTMENT, CREATE_TABLE_NOTIFICATION,                         CREATE_TABLE_QUERY, CREATE_TABLE_QUERY_REPLIES, CREATE_TABLE_ATTENDANCE, CREATE_TABLE_TASK, CREATE_TABLE_APPLIED_LEAVE, CREATE_TABLE_NOTIFICATION_READ, CREATE_TABLE_CHECK , CREATE_TABLE_HOLIDAY, CREATE_TABLE_INDIVIDUAL_NOTIFICATION, CREATE_TABLE_PERFORMANCE, CREATE_TABLE_QUERY_HANDLER , CREATE_TABLE_NOTIF_LIKES];
    
    static var UUID_DEPT_1 = UUID().uuidString
    static var UUID_DEPT_2 = UUID().uuidString
    static var UUID_DEPT_3 = UUID().uuidString
    static var UUID_EMP_1 = UUID().uuidString
    static var UUID_EMP_2 = UUID().uuidString
    static var UUID_EMP_3 = UUID().uuidString
    static var UUID_EMP_4 = UUID().uuidString
    static var UUID_EMP_5 = UUID().uuidString
    static var UUID_EMP_6 = UUID().uuidString
    static var UUID_EMP_7 = UUID().uuidString
    static var UUID_QUERY_1 = UUID().uuidString
    static var EMP_COL_1 = "INSERT INTO "+TABLE_EMPLOYEE+"( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+"  ) VALUES ('Velmurugan', 101, '"+UUID_EMP_1+"' , '9094569870' , 'vel@zohocorp.com' , 'MALE' , 'kalaingnar nagar, \n avadi, \n chennai' , '"+UUID_DEPT_1+"' , '"+UUID_EMP_2+"' , 'Chennai, India' , 'Project Trainee ' )";
    static var EMP_COL_2="INSERT INTO  "+TABLE_EMPLOYEE+" ( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+" ) VALUES ('Bob',102,'"+UUID_EMP_2+"','8667391809','bob@zohocorp.com','MALE','zoho','"+UUID_DEPT_1+"','"+UUID_EMP_6+"' , 'Chennai, India' , 'Member Leadership staff ' )";
    static var EMP_COL_3="INSERT INTO  "+TABLE_EMPLOYEE+"( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+") VALUES ('Allen',103,'"+UUID_EMP_3+"','9444230291','allen@zohocorp.com','MALE','zoho','"+UUID_DEPT_2+"' ,'"+UUID_EMP_6+"' , 'Chennai, India' , 'Member Leadership Staff' )";
    static var EMP_COL_4="INSERT INTO   "+TABLE_EMPLOYEE+"( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+") VALUES ('Mahin',104,'"+UUID_EMP_4+"','9445234489','mahin@zohocorp.com','FEMALE','zoho', '"+UUID_DEPT_2+"','"+UUID_EMP_3+"' , 'Chennai, India' , 'Member Technical Staff ' )";
    static var EMP_COL_5="INSERT INTO  "+TABLE_EMPLOYEE+"( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+") VALUES ('Sharmila',105,'"+UUID_EMP_5+"','7010366719','sharmila@zohocorp.com','MALE','zoho','"+UUID_DEPT_1+"' ,'"+UUID_EMP_2+"', 'Chennai, India' , 'Member Technical Staff ' )";
    static var EMP_COL_6="INSERT INTO  "+TABLE_EMPLOYEE+"( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+") VALUES ('Sridhar Vembu',001,'"+UUID_EMP_6+"','8124362002','svembu@zohocorp.com','MALE','zoho','"+UUID_DEPT_3+"' ,'-', 'Chennai, India' , 'Chief Executive Officer ' )";
    static var EMP_COL_7="INSERT INTO  "+TABLE_EMPLOYEE+"( "+COLUMN_EMP_NAME+","+COLUMN_EMP_ID+","+COLUMN_UNIQUE_ID+","+COLUMN_EMP_PHONE+","+COLUMN_EMP_MAIL+","+COLUMN_EMP_GENDER+","+COLUMN_EMP_ADDRESS+","+COLUMN_EMP_DEPT_ID+","+COLUMN_EMP_REPORTING_ID+","+COLUMN_EMP_LOCATION+"," + COLUMN_EMP_POSITION+") VALUES ('Lakshman',106,'"+UUID_EMP_7+"','7010365751','thalaivan@zohocorp.com','MALE','zoho','"+UUID_DEPT_2+"' ,'"+UUID_EMP_3+"', 'Chennai, India' , 'Member Technical Staff ' )";
    
    
    static var DEPT_COL_1="INSERT INTO "+TABLE_DEPARTMENT+"("+COLUMN_DEPARTMENT_ID+" , "+COLUMN_DEPT_UUID+","+COLUMN_DEPARTMENT_NAME+","+COLUMN_DEPARTMENT_HEAD_ID+","+COLUMN_DEPARTMENT_DESCRIPTION+") VALUES (1,'"+UUID_DEPT_1+"','Mobile apps','"+UUID_EMP_2+"','Creating Android and ios app');";
    static var DEPT_COL_2="INSERT INTO "+TABLE_DEPARTMENT+"("+COLUMN_DEPARTMENT_ID+" , "+COLUMN_DEPT_UUID+","+COLUMN_DEPARTMENT_NAME+","+COLUMN_DEPARTMENT_HEAD_ID+","+COLUMN_DEPARTMENT_DESCRIPTION+") VALUES (2,'"+UUID_DEPT_2+"','CRM Web','"+UUID_EMP_3+"','Development of web application of CRM team');";
    static var DEPT_COL_3="INSERT INTO "+TABLE_DEPARTMENT+"("+COLUMN_DEPARTMENT_ID+" , "+COLUMN_DEPT_UUID+","+COLUMN_DEPARTMENT_NAME+","+COLUMN_DEPARTMENT_HEAD_ID+","+COLUMN_DEPARTMENT_DESCRIPTION+") VALUES (3,'"+UUID_DEPT_3+"','Executives','"+UUID_EMP_3+"','Higher level managing position');";
    
    
    static var ATTEND_COL_1  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME)  , \(COLUMN_UNIQUE_ID) )  VALUES( 1561228200, 1559531700, 1559564280,  '\(UUID_EMP_2)' )"
    static var ATTEND_COL_2  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME)  , \(COLUMN_UNIQUE_ID) )  VALUES( 1561314600, 1559448300, 1559482380,   '\(UUID_EMP_2)') "
    static var ATTEND_COL_3  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME)  , \(COLUMN_UNIQUE_ID) )  VALUES( 1561401000, 1559361300, 1559394720,  '\(UUID_EMP_2)' )"
    static var ATTEND_COL_4  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME) , \(COLUMN_UNIQUE_ID) )  VALUES( 1561487400, 1559275190, 1559307300, '\(UUID_EMP_2)' )"
    static var ATTEND_COL_5  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME) , \(COLUMN_UNIQUE_ID) )  VALUES( 1561573800, 1559185200, 1559221200,   '\(UUID_EMP_2)' )"
    static var ATTEND_COL_6  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME)  , \(COLUMN_UNIQUE_ID) )  VALUES( 1561919400, 1559104920, 1559137320, '\(UUID_EMP_2)' )"
    static var ATTEND_COL_7  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME)  , \(COLUMN_UNIQUE_ID) )  VALUES( 1558981800, 1559013780, 1559046300,  '\(UUID_EMP_2)' )"
    static var ATTEND_COL_8  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME) , \(COLUMN_UNIQUE_ID) )  VALUES( 1558895400, 1558928280, 1558960500,  '\(UUID_EMP_2)' )"
    static var ATTEND_COL_9  = "INSERT INTO \(TABLE_ATTENDANCE) ( \(COLUMN_DATE_DETAILS) ,\(COLUMN_CHECK_IN_TIME) , \(COLUMN_CHECK_OUT_TIME) , \(COLUMN_UNIQUE_ID) )  VALUES( 1558809000, 1558842000, 1558874700, '\(UUID_EMP_2)' )"
    
    static var HOLIDAY_COL_1 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1546281000, 'NORMAL' , 'NEW YEAR' )";
    static var HOLIDAY_COL_2 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1547404200, 'NORMAL' , 'PONGAL' )";
    static var HOLIDAY_COL_3 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1548441000, 'NORMAL' , 'REPUBLIC DAY' )";
    static var HOLIDAY_COL_4 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1555612200, 'OPTIONAL' , 'GOOD FRIDAY' )";
    static var HOLIDAY_COL_5 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1556649000, 'NORMAL' , 'LABOURS DAY' )";
    static var HOLIDAY_COL_6 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1565807400, 'NORMAL' , 'INDEPENDANCE DAY' )";
    static var HOLIDAY_COL_7 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1569954600, 'NORMAL' , 'GANDHI JAYANTHI' )";
    static var HOLIDAY_COL_8 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1570386600, 'NORMAL' , 'AYUTHA POOJA' )";
    static var HOLIDAY_COL_9 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1570386600, 'NORMAL' , 'DEEPAVALI' )";
    static var HOLIDAY_COL_10 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1572201000, 'OPTIONAL' , 'DEEPAVALI' )";
    static var HOLIDAY_COL_11 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1577212200, 'NORMAL' , 'CHRISTMAS' )";
    static var HOLIDAY_COL_12 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1514745000, 'NORMAL' , 'NEW YEAR' )";
    static var HOLIDAY_COL_13 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1515868200, 'NORMAL' , 'PONGAL' )";
    static var HOLIDAY_COL_14 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1561905000, 'NORMAL' , 'REPUBLIC DAY' )";
    static var HOLIDAY_COL_15 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1522348200, 'OPTIONAL' , 'GOOD FRIDAY' )";
    static var HOLIDAY_COL_16 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1525113000, 'NORMAL' , 'LABOURS DAY' )";
    static var HOLIDAY_COL_17 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1534271400, 'NORMAL' , 'INDEPENDANCE DAY' )";
    static var HOLIDAY_COL_18 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1538937000, 'NORMAL' , 'GANDHI JAYANTHI' )";
    static var HOLIDAY_COL_19 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1538418600, 'NORMAL' , 'AYUTHA POOJA' )";
    static var HOLIDAY_COL_20 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1541529000, 'NORMAL' , 'DEEPAVALI' )";
    static var HOLIDAY_COL_21 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1541615400, 'OPTIONAL' , 'DEEPAVALI' )";
    static var HOLIDAY_COL_22 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1545676200, 'NORMAL' , 'CHRISTMAS' )";
    static var HOLIDAY_COL_23 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1577817000, 'NORMAL' , 'NEW YEAR' )";
    static var HOLIDAY_COL_24 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1578940200, 'NORMAL' , 'PONGAL' )";
    static var HOLIDAY_COL_25 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1579977000, 'NORMAL' , 'REPUBLIC DAY' )";
    static var HOLIDAY_COL_26 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1586457000, 'OPTIONAL' , 'GOOD FRIDAY' )";
    static var HOLIDAY_COL_27 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1588271400, 'NORMAL' , 'LABOURS DAY' )";
    static var HOLIDAY_COL_28 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1597429800, 'NORMAL' , 'INDEPENDANCE DAY' )";
    static var HOLIDAY_COL_29 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1601577000, 'NORMAL' , 'GANDHI JAYANTHI' )";
    static var HOLIDAY_COL_30 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1602268200, 'NORMAL' , 'AYUTHA POOJA' )";
    static var HOLIDAY_COL_31 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1605292200, 'NORMAL' , 'DEEPAVALI' )";
    static var HOLIDAY_COL_32 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1605378600, 'OPTIONAL' , 'DEEPAVALI' )";
    static var HOLIDAY_COL_33 = "INSERT INTO \(TABLE_HOLIDAY_LIST) ( \(COLUMN_HOLIDAY_DATE), \(COLUMN_HOLIDAY_TYPE), \(COLUMN_HOLIDAY_REASON) ) VALUES (1608834600, 'NORMAL' , 'CHRISTMAS' )";

    
    static var QUERY_HANDLER_COL1 = " INSERT INTO \(TABLE_QUERY_HANDLER)  ( \(COLUMN_QUERY_TYPE) , \(COLUMN_QUERY_INCHARGE) ) VALUES ( 'PayRoll' , '\(UUID_EMP_2)' ) "
    static var QUERY_HANDLER_COL2 = " INSERT INTO \(TABLE_QUERY_HANDLER)  ( \(COLUMN_QUERY_TYPE) , \(COLUMN_QUERY_INCHARGE) ) VALUES ( 'Others' , '\(UUID_EMP_3)' ) "
    static var QUERY_HANDLER_COL3 = " INSERT INTO \(TABLE_QUERY_HANDLER)  ( \(COLUMN_QUERY_TYPE) , \(COLUMN_QUERY_INCHARGE) ) VALUES ( 'Insurance' , '\(UUID_EMP_5)' ) "
    
    static var TASK_COLUMN_1 = "INSERT INTO Task ( TaskName ,EmpId ,TaskDetail, StartDate ,EndDate ,TaskAssigner, Status, TaskId ) VALUES (\'Complete your first task\' , '\(UUID_EMP_2)' , \'Please try completing your first task within the given period so that you can make your place further steady. No extended time will be provided to you and you must complete it as soon as possible. Hope you complet\' , 1547145000 , 1550601000 , \'9347788F-C805-463D-9F21-5F7F520D41D8\', \'Completed\' , '\(UUID_EMP_6)')"
    static var TASK_COLUMN_2 = "INSERT INTO Task ( TaskName ,EmpId ,TaskDetail, StartDate ,EndDate ,TaskAssigner, Status, TaskId ) VALUES (\'Ask your trainees to complete the work\' , '\(UUID_EMP_2)' , \'Your trainees had enough time to learn about the new summaries and its time for them to get and work into the product. So have a look at their performance and make them ready to work at the product. Congrats!!\' , 1559327400 , 1561919400 , \'64CBF58A-5413-492F-9E14-A10E801F5488\', \'Incomplete\' , '\(UUID_EMP_6)')"
    
    static var NOTIFICATION_ROW_1 = "INSERT INTO \(TABLE_INDIVIDUAL_NOTIF) (  \(COLUMN_NOTIF_SUBJECT) ,  \(COLUMN_NOTIF_DETAILS) , \(COLUMN_NOTIF_SENDER_ID)  ,  \(COLUMN_NOTIF_RECIEVER_ID) , \(COLUMN_NOTIF_DATE) ) VALUES ( 'Task', 'Sridhar Vembu have assinged you a task and make sure you complete the tasks given and inform them with proper notice. \n Thanks!!!' ,'" + UUID_EMP_6 + "','\(UUID_EMP_2)' , \(Int(Date().timeIntervalSince1970)) );";
   static var PERFORMANCE_ROW_1 = "INSERT INTO \(TABLE_PERFORMANCE) (  \(COLUMN_UNIQUE_ID) ,  \(COLUMN_PERFORMANCE_DATE) , \(COLUMN_PERFORMANCE_COMMENTS)  ,  \(COLUMN_PERFORMANCE_ENTHUSAISM) , \(COLUMN_PERFORMANCE_SPONTANITY) ,\(COLUMN_PERFORMANCE_RESPONSIVENESS) ,\(COLUMN_PERFORMANCE_TIME_MANAGEMENT) , \(COLUMN_PERFORMANCE_OVERALL_PERFORMANCE) ) VALUES ( '\(UUID_EMP_2)' , \(Int(Date().timeIntervalSince1970)), 'Your performance is well and good but need few imporvements in time mangement. Hope you reach that soon. Keep Going!!!' , 5 , 4 , 5, 3 , 4 )  ";
    static var QUERY_1 = "INSERT INTO Questions ( QueryID, SenderId,RecieverId,QuerySubject,queryAsked,QueryDate ) VALUES ('\(UUID_QUERY_1)', '\(UUID_EMP_2)' ,'\(UUID_EMP_5)',\'Insurance premium showing not paid\',\'I have paid the insurance premium last month but I have received the message stating that I haven’t paid the premium and should pay as soon as possible. Please look into my query and solve it as soon as possible\',1561962264) "
    static var  QUERY_REPLY_2 = " INSERT INTO Replies ( QueryID, Reply, ReplierId, QueryDate ) VALUES( '\(UUID_QUERY_1)', \'Sorry that was due to some server side errors it was ok now and you don’t need to worry. Your insurance is paid!! Thankyou\', '\(UUID_EMP_5)', 1561962982 )"
    static var LEAVE_COLUMN_1 = "INSERT INTO  LeaveApplied   ( UniqueId  ,  ReasonId ,StartDate ,  EndDate ,  LeaveDetails ,DepartmentID ) VALUES ('\(UUID_EMP_2)', \'Team Trip\', 1559068200 , 1559241000 , \'Team trip\' , '\(UUID_DEPT_1)');"
    static var LEAVE_COLUMN_2 = "INSERT INTO  LeaveApplied   ( UniqueId  ,  ReasonId ,StartDate ,  EndDate ,  LeaveDetails ,DepartmentID ) VALUES ('\(UUID_EMP_2)', \'Compensatory Off\', 1560882600 , 1560882600 , \'K\' , '\(UUID_DEPT_1)');"
    
    static var UPDATECOLUMN = [EMP_COL_1, EMP_COL_2, EMP_COL_3, EMP_COL_5, EMP_COL_4,  EMP_COL_6 , EMP_COL_7 ,DEPT_COL_1,DEPT_COL_2, DEPT_COL_3, ATTEND_COL_1, ATTEND_COL_2, ATTEND_COL_3, ATTEND_COL_4, ATTEND_COL_5, ATTEND_COL_6, ATTEND_COL_7, ATTEND_COL_8, ATTEND_COL_9, HOLIDAY_COL_1, HOLIDAY_COL_2, HOLIDAY_COL_3, HOLIDAY_COL_4, HOLIDAY_COL_5, HOLIDAY_COL_6, HOLIDAY_COL_7, HOLIDAY_COL_8, HOLIDAY_COL_9, HOLIDAY_COL_10, HOLIDAY_COL_11, HOLIDAY_COL_12, HOLIDAY_COL_13, HOLIDAY_COL_14, HOLIDAY_COL_15, HOLIDAY_COL_16, HOLIDAY_COL_17, HOLIDAY_COL_18, HOLIDAY_COL_19, HOLIDAY_COL_20, HOLIDAY_COL_21, HOLIDAY_COL_22, HOLIDAY_COL_23, HOLIDAY_COL_24, HOLIDAY_COL_25, HOLIDAY_COL_26, HOLIDAY_COL_27, HOLIDAY_COL_28, HOLIDAY_COL_29, HOLIDAY_COL_30, HOLIDAY_COL_31, HOLIDAY_COL_32, HOLIDAY_COL_33,QUERY_HANDLER_COL1, QUERY_HANDLER_COL2, QUERY_HANDLER_COL3,TASK_COLUMN_1,TASK_COLUMN_2,NOTIFICATION_ROW_1, PERFORMANCE_ROW_1, QUERY_1, QUERY_REPLY_2, LEAVE_COLUMN_1, LEAVE_COLUMN_2];
}
var db = DatabaseController()
